spring:
  application:
    name: fitness-assistant

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_assistant
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0


  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    root: INFO
    org.flywaydb: INFO
    org.hibernate.SQL: DEBUG
    com.example.fitness_assistant: DEBUG