spring:
  application:
    name: fitness-assistant

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_assistant
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0


  cache:
    type: caffeine
    cache-names: exercises, food, muscles, userProfiles, targets
    caffeine:
      spec: maximumSize=500,expireAfterAccess=1h

jwt:
  secret: ${JWT_SECRET}

app:
  init-data:
    directory: data/

logging:
  level:
    root: INFO
    org.flywaydb: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    com.example.fitness_assistant: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: db
  health:
    db:
      enabled: true