CREATE TABLE IF NOT EXISTS food (
    id BIGSERIAL PRIMARY KEY,
    barcode VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    brands VARCHAR(255),
    kcal DOUBLE PRECISION,
    proteins DOUBLE PRECISION,
    fats DOUBLE PRECISION,
    carbs DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS exercise (
    id BIGSERIAL PRIMARY KEY,
    muscle_group VARCHAR(100) NOT NULL,
    muscle_detail VARCHAR(100) NOT NULL,
    exercise_name VARCHAR(255) NOT NULL,
    description TEXT
);