CREATE TABLE IF NOT EXISTS food (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    brands VARCHAR(255),
    kcal DOUBLE PRECISION,
    proteins DOUBLE PRECISION,
    fats DOUBLE PRECISION,
    carbs DOUBLE PRECISION
);
CREATE TABLE IF NOT EXISTS exercise (
    id BIGSERIAL PRIMARY KEY,
    exercise_name VARCHAR(255) NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS exercise_muscle (
    id BIGSERIAL PRIMARY KEY,
    exercise_id BIGINT NOT NULL REFERENCES exercise(id),
    muscle_group VARCHAR(100) NOT NULL,
    muscle_detail VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'USER'
    );

CREATE TABLE IF NOT EXISTS user_profile (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    name VARCHAR(255),
    birth_date DATE,
    weight DOUBLE PRECISION,
    height DOUBLE PRECISION
    );